version: '3.8'

services:
  monsite-php:
    image: php:8.2-apache
    container_name: white-lotus
    volumes:
      - ./src:/var/www/html
    environment:
      - VIRTUAL_HOST=white-lotus.tiphereth.site,www.white-lotus.tiphereth.site
      - LETSENCRYPT_HOST=white-lotus.tiphereth.site,www.white-lotus.tiphereth.site
      - LETSENCRYPT_EMAIL=admin@tiphereth.site
    networks:
      - web
    restart: unless-stopped

networks:
  web:
    external: true
